language: node_js
node_js:
  - '0.10'
branches:
  only:
    - source

before_install:
  - gem install bundler
  - bundle --without=development
  - npm install -g grunt-cli

script:
  - grunt build

after_success:
  # Setup SSH key to push to github
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.name "Bradley Grzesiak"
  - git config --global user.email "listrophy@gmail.com"
  - grunt deploy

env:
  global:
    - secure: "hrr0QWQxrl5bC3KVobz7u52oExRMiXmFJZJ/ObNudz/9QDrqbYCoTCBcVw/9e2bQsLqzPlJCFPuoJ0FQEY5mXWGRYJf4kunAHH35GZfvQ9RjUBEbXGCaGayksAZ2Htc7ouwwH6n1a50E4ou8XGiQcZa2glJBqsqBlSQiY3LTZhQ="
    - secure: "SHz4pF6JNFhZCUilDwobpv+uHqwKbQehgKDfgy5eUzJquHGK/P9PBBZC04S/hMXL+rqB6dKLZnihSEwkY2qn0g6M4q37/KpHHWQOMxAOqYn4QUj3X/n/o+gYtUHfr09zo5GDgf4wbqmq0QwCOLI+vKRO6kI0MIIJ5BgJpuBD+7I="
    - secure: "AYTBVSibR6eovQu33WLBnHmNAbCB7v/dFaWs00XcN6Oc/SgjEMNex9j8KckTQApgE5Jd9m2KSrk+4t3hdkyKT9Vb8HO27vXY1AUpzGykzXJ34cjJgW9uFOGyyieJ1VehOAibDZ+8NTNVpYa64Ppx0l46x/9gGnTLPeOjwE3SIcc="
    - secure: "YRyZqspD0ppJzk/MKdW5EvoLaeVxvO2s7onkDRwjYV4ZXIjv35WA+LvdoYV4w628wXDHKL7Xf5HXNh0hutEY+n2zksOwpVvbz1H8TsFpYEZlCDnTVogOrnYO4ZhhPvfqV6JUYObpMnkwTAU/+gp279mcAeBZttB02vG1xtLIMfE="
    - secure: "NVqDna9oqmXBwZ2zpDoD9+iku0/lAXVyrwADdOBsGegQxtKvs5eDx4pd6B1nPZjCQkO8yeZsdksxKpLcc4mare4N872GXhBa9th6lfGzR2PypT1EWiyd7D7wOmuy3v5U15H9osFAZ+9kbXdO6eEOt8xTvccnrSJOB1zxG/sEz2o="
    - secure: "KoL9LIgNErY3lw63KjHsFZEOjh2c9ZIxN/m4qPX++qcMX0tiBs9BNymMfjZwG9VfOYo51DMjoSxnuMlSvjNlaP9e4ErZ9DbUeWIITmMg0EF7xTSZwbCL0D7xawlsS3QTST/zeKb66PEL0N5mw53eGA1WP2NjQt+7V00s5MA8XJk="
    - secure: "imjwUgOqFHX+dEBW16YD6BGsMzEWgUray6DsyfvQnHLxplB1typN/uDI+ZDMrhkx/2qYA4QuBjGN7H3O18sXzLg1F3DoN43XClFybilq+qLwmxs5q6UErjneeuDg0FITkoCWiJuSoR5Y8tqz0SKR1V4r3IeyY2MknlSAEa6pKY0="
    - secure: "qPkWFz188R5KQydv444IdRROBQa+zuaY2QxDmWcv9W9UARqTWlbHMWSxmJx/61IQfxKDU7DtwGtwHC6L9EjJyVZ1Vp+V+fJ704VyMtrPsuL55x9W1uSqjhoX/k4jN72d2kM6Br2Vd3a3M9M+C/svets6LbWkACN3lEveYseXXA4="
    - secure: "eP8f7LHaFu5vReyLD47HH1Xne69sEzP0yJiSa8YTsFUzNLTTPGzf/DKbMTq0WsMuMaKsWtMFwZDCnx4e6UdYAYIXKj5Bw3o/cZCx8vo2+0FWF1EfkiALUeIs549vx1uyq84cUK9aJQcuq5xPYpSlsUGV1pLy49iEJL1ZYcsbV3I="
    - secure: "WsbgntxnVavBKjvYUm82Ad0P5QLlqNznPY05tKZ+yf63UzFyTHN3Z1yC2a1ZFqVUnPRmQrXNcJxjmW4s0+R5I29AKO66jSGOxkr40xrhJIdnzuBZ2zMV1Rk+AQ8DiJ1XY15wpnY8DvYwgZE/S/CEpKezW/fusm0OUkxHF4LlT1g="
    - secure: "Gr5Hlkmrh/950XCppbF3dWLd8L6DYbKt7QtGizCIAryLHw9k8cImapkbvYx+fPtGrtbfZXDy4gryU6hhPg9s5k/x5m97QVyg5QCVjGYbERYgBMuMhFk58j2/HpVd0Sn+CznZ/jFB0dvmw9B7tn30ZCal8QIpzs9/GUC7w6hbQuE="
    - secure: "GJqRd4OMG9enE59meo4K0sMhPNIph+E3SpjD/l8bX32k4dMaUvkxHP4+J0aaLFuNkBRkSFgpWD2LxEnKl4oR+DAln2JKQEyO4VHHx2AFqTQGq3ilKGCs1FmvADt4enzqKUMj30b7LS07/aUrf+nbJXpuABRa3eYKjqkVCg5oksE="
    - secure: "GOdsWcnIHwt8XxCDpqQT6agOuCRrtIx6TyqrgKY3nwnh7DZWH1MpLFyk7SKG0yNdWJuKNHIgGWK3dnJugt6+1CXxkib7eKJCXvreq9a+A33p/2wQnXnWMwwlPCTdzbS/IrTdLATFAF9viUAyNqkKJ7Bbxh4UvscylD0mPHQerH4="
    - secure: "hkE1GnkXWgEPelyxnCA+P11Ugll2vNRCigRjHQ/kjpxcW3QOzOCZbh610BSM2Fz5JMgiOqITOVN2OZWaAP1c2YdZCEHc1F9t06ukIGVrHNg2z1ZDvSyyzm0RB6+nLh78roFJMUzRjYQVhdbC7WPjhcpsTux/1k68s6x2a4TZ8AU="
    - secure: "HMU9jb8oevGeEF1hu6YY1z9EgtKL1wrYDQkoMjTMoEEp9noFb9f/xFRYgFuBDJvHBf094ktjTOLYo5No6zudowld38N30gl4pSyWAEvcUSElzeiHuzSuRuM2aqPV595YYreIIMyA7ycFu3e4sJJ8Y6OtrfAc/jyhlJScEq1bzmM="
    - secure: "Sa1za1vJeVps26wWL1/aDb7rre0Zd9Sqd/JJY1h34GKL+bsKPGgUk60ktvDpUEkqvEvNUwxQyc1+D3u4vXkGQH0ndO6O0MVq0fJrgnbMyKT69cS6YjHqski/wU+mGmTPLHVIsQPR/7Ti3J5Z+kcfyehxo0bKZlGJgnmzAnef4oY="
    - secure: "RDLassXc8OTEzhha5oChl0xdWs9c3BzDt/1YOo8r9ensNToPIZ1tggfuyxMkVksQbgrh9XYBiHV+uxliwW5FD14qzTSpTFATDtGlrBLTMarySzR/kAr1jTEVUVS+no7la9xPVJuGHNkQuC5J9GpF33GXIHpY3CB6C2Rqht0LOQQ="
    - secure: "I5ndGkVrGsM67SmH4M/opHybK9BgrtGRzFpTVqUF4xkFNNh6Ehc+O7YE8gTTc93vDi0aaiDAoDt8Kfyvf2lQUqOwfqyxzgTUzVnFZxhStCZzgfGZtYb/OSIFUz5D9zeeE46sEgB1bkmSHNvIPa/LECBFI8LiNxf6Je7YpLNgJco="
    - secure: "R8FuL3ph9jl0V66Txv8SRZDOb9dZzDh5oJcpRGKMs++iLYAe3uZ+w0/P2uNt+Kee+q8tb47dJFP6llwYkT/pC/QFucb44/5MFCRKLIKBhvHWag7vzgVL3A/OU8W0RfNWTX0zZnTLuo4/y4ZDHV2ZKGTds0qZwGCqdxiAyMkIUhU="
    - secure: "GsiOxnvlsn8Id+EV7zB3VJQDQDako+gDKfft/cIc42pjEQPUJ/Q812D1vkjF3CXV+Pgm8zilTedgwmCXzaVQ8keXAH2SeZ6h//gVXdph9AbYraJDGfpMOy65z6n4w8/6yjxTfN/QCvLpQgVP1S5kOZQZ2NhVT0jn5zPMxfFc760="
    - secure: "dSwMg2lkx47N11OOi+gDEg4F5yqgkVRplN5ZeBoEuzRP2V9Twd3tBs+2ZYTnCrvG9F/ZO5aERaPm9+JS3RQXRMjQKz28p7P6KPqJooeqipTCiXWhdaN+5y1n9W4rDQqh7Ad3BwbN9Ij/LvVDLJ0lkidX2/mkNN6CNFM3yJkrgCg="
    - secure: "YwROp3VCEeWummpFYUr2ofcPVYPQmHRUX3T9wQGMZcxBt+TKViaU6n9T+C3KpEQfyp9ya+ifguJ8jiNw6jEnTlDi8ztnR6gBumuRT07OflJweGY6JlqilEVyFzDrtYQjbMZtBakD9dUXsFYk2dvYPeZlD9Nj+BHJPG/73Cd5Sow="
    - secure: "W717+qwK8gMx0acetSSC/jWu1wAOIPT0aG4922dxkRSXtOwKiBqfzc4Wme/cco9HLww3FiDR5euwFRKk59PkxE2yRtuY6Y8sZ1Bl/m65yQ7o0oN88dqWSp/dqtaDxvwgO/08hJNUFAH09fHUPeYLhCN7PfV2p3fEK+ZbdLGJccA="
