language: node_js
node_js:
  - '0.10'
branches:
  only:
    - source

before_install:
  - gem install bundler
  - bundle --without=development
  - npm install -g grunt-cli

script:
  - grunt build

after_success:
  # Setup SSH key to push to github
  - echo -n $id_rsa_{00..30} >> ~/.ssh/id_rsa_base64
  - base64 --decode --ignore-garbage ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git config --global user.name "Bradley Grzesiak"
  - git config --global user.email "listrophy@gmail.com"
  - grunt deploy

env:
  global:
    - secure: "YKWW5Cu5QqHIYntBiA1wb2S1tnU1gUW6+YAeU/wu/aQGgyA+wKqWjqFOoJOFjqUWcN0dJ8pZfas1D5YjG/Fq3l4/XJQ3KtezTsgsWwqu2hftGMIB1m4HvZxJIWn1mZRXf03eDAKeyGM+4VeR7fqdj91RPMDkdyHgHPTDXj3lg6Q="
    - secure: "gxoUQq4WiVnWKld4+5uNUWsKSVSiCczZ13jaNzApLcD2PoKX2wIhzjE8jbQgZD8JPVIGnZAaI0AzH0IrwMM5apl8oJWp60Hs47w1mcrznrkTZm41Br3L4unuHWd1xz4hP71sMTJOLelxFH1D7KIn7xumH9uqcsKJ4wR08g6WP9w="
    - secure: "oytLdka9MLVAfhqdr0oSQrkyujz/mPhNXPemqCRrPZY+E9DuaeP57spdK6/wCcjLAHPnPGWjD0rEi8IMeDg4AmNWE+8swsRw3eYlJUU4bvpCjNnesbtJPsWLK9XVKHDYljdkQ4/DicbljeuH7Dpqrfe+KvWFV6HHL2eH29/DOKw="
    - secure: "NKZqv9ufFNbBRgKKH3z9Bt0tJZlwk4XZYM4m9wza12D9oBWpp5qaNB9wtRB+wKXzAy3T0eroynufleKOtoWgLqQj+VpkCfsQ5x1WKQbcDPPgh4Pj0j22ZTc0vJKUJdaSfKxM6aNoEgd+QiWTzqOKRPNm8s/9avHvBMny9hZuEgE="
    - secure: "XrKUy1VHTdhVZuEpaF70/qICzhXCIztS/lkCTmPWo8XP6pbKU/ZpKcprY+gWhtxd93K2hCP9zrZc/g9jQScYklXsdmgN9dvNjmcHiZPf1tAZ9P7PNO2SB4DqlBolgjzQoMTIE2x9WzVuZByVLJsZpzJaANzOEVXIcBzGjPcaAtE="
    - secure: "B/alTpHaVyLRrOvdoTXw/W0TiuZBA2+Sq4ZTXF9UqfWd3sAi7pGebkyDHTLNnXzbHDhmzE98QFrhEr94OTUqJAohQQZeMGt6IvGlxSWFmDdpnuh19cSXUcUIAIxwi1P13Y3yxaYAQhUh1Z28SYw9EpWPkYYQRbB+w2PySn25Xuc="
    - secure: "FNl1f82Ao6vMeDJp4MGZClCdzTsLWmROujbW0VSHIeoWYFnQKe0D4EkOkXEbnQZPpQN5Nf5aA0KW5/r4vbDA07g2+00OgHD37C0w8K5qxgZzSIxqdUxh6fQ5x4O2TGLXhuMCFp5ZRBq9qWhZEC4leVoroaORT0xhwCcOqlv8uf8="
    - secure: "KMoVh8sqpAV2AEUh20k7F8a8Z27+wEga+QA/dHmJqJUvGCZAapPxZQUtdL/RALP/tVn7o6PClb3MM1qmPDzzvwF4HKeXmLsiFgCi8GzIu0OTa3m/XEG8NkR++8+cGzaRhNz4Twi6WfJlM6blZtSBlAp3jKDeds/xwHFKIuvNoQ8="
    - secure: "qIl7fM1PGBZLF4fK9VuuVkNrhMYDiMjhZ+tMCLKZ6K5s6XCKZ+I3Hq21k+j3TeCx/Fg2hopDfVB9cbhYtZquVPNaaoJTS44oJ4jrxsihOIV/FP7nr6r76dEaKaXmSr2z4VevjC7ZSkZySpsUL6ToBSi2Go2QP96Z9jTlGxSWkyU="
    - secure: "CS4CFtuXLQztFRXVMw8ZBHILHkVtYOcnD9ALymGKS2NTIXRDjfZv+2CbziW3qTZ9QXOSUD+JGsDwT8itWBpX0fcoEM3xs8RsnIwnwZGHMsc7cRGvJbaCCfA/e0zpKOmJICljVsQbeEHqOkewRdwI159i/JfuFPVYIpSXHCrXrwo="
    - secure: "dwIUwdAIMMYc21TlMJDaYwmFuvtsEZAa0xnM5fuc6ULaG8s3tcbqUKgsUBS5qju9IYWleJYm0Ch/PpUvH2NCETISuq+sSCecPhd08FBD/69J6c3RJlmG3h34J6zTjqvMl7HM0L7+I43bjvwJSMNnDz4MIYCtRvu7kuH1WbunDqc="
    - secure: "CLlw9VlhDEnFhVNaJuEH7+x0/QDlhinHJBKN5OdCY1OpjU+1QLrr46ynW/sZwzJL5dQmoR1W7MYY1f5wP5VUn474G+OCqdEqkUDdVG7IyZ9lVNmEpzhD1TsWmOm+OOtWqz6RDjqWWpjMaXw0o7aTIsGZ+fyBLsHoQ9hutQUiGC8="
    - secure: "VAByJ2aG+iwMQiqFDC9Z3hhCvjftiobQDNkdXf0aVdjHsOb3sDJonLHfQrChae1BaU9l3enc52d/qoO9VWklI8YnTs8OLjteYv7EFDm20tALxaN3+rxL8j1e7IvyihRgmf7u00kizwq7houos4mtbQCGTBvxRwDAQtIcIUgeP88="
    - secure: "lcveIgAjwljkaDBiGMGRjf/SwKOU0Je1EM5yXFbTQJgtOhUl6QEcE+/RW6sbb5R7dvmQQJT6TFZfDnS/HIdonPOz/WwvOKUe/CDqdFN/Y08rnZ3Kz/h1C+/3N4grpQteaMB18ueP0tXfrVSH62GtrKtZs6JvGqVF+HE+FtqsMmQ="
    - secure: "mJiztHMA9UwSgsStCAnf65iZLV1MsNEte6hyal4JSZdkgmRrn3eJN0HqcIR6k+hSjHUsS668wl/5S2PbKfdbqbtmGuvy6/BE96cT4R8rRI7RJ2sLloppsMZBeBSUlRbViCgYNJ/fI7kfDFwDFZo69KSX15w85XkmcbF9hl9K3GE="
    - secure: "XNT2eOSrYtTrHiofQETZ21WO8gkkelPD+FE2D2gMFcv0F9K9lmbkb1wjJMqwLHaMl2Kg6WlxMFWCMdbm19/bafzoa6+FTdUjZwbwO2c4nSmmLHqNkLqJ3BTEUwQ4wSmOjIRQvff0msgvWXpT5IM2qMvTP8+PIFl/6egJg9GnztE="
    - secure: "Fg7RA58ZqQDvS+fvDH6m2tTRwGFWi1qQCJO/IcMjt94CIrb/IESmc8zLXUjV+h71KIRj+RFQJWULWWpcS+XtLuedmmSqT1VWGgp9et/zOdI6edYWrS2Bx0sqpqS9GvfTTbTvPO8EFOfTrVTXgTa6U8bOc6/Hyr4Dg9bP/rfwKAM="
